name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-pbix:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v3

      - name: Verificar arquivo Power BI
        run: ls | grep '.pbix' || echo "Arquivo Power BI não encontrado!"
